[GNIR-17] Merge dev into master
REDLab-Team/gnirps pull request #28
Opened 2021-10-29 07:51 UTC by AdamJouenRL

2021-11-02 08:19 UTC, vainj requested changes

2021-11-02 08:19 UTC, vainj commented on demos/cat-api-jwt/pom.xml
> +                <version>${kotlin-maven-plugin.version}</version>
A conserver ? Si oui, pourquoi dans le module `demos` de GNIRPS ?

2021-11-02 08:19 UTC, vainj commented on gnirps-origin/pom.xml
> +        <maven-javadoc-plugin.version>3.3.1</maven-javadoc-plugin.version>
Pourquoi la montée de version de ce module est nécessaire ici ?

2021-11-02 08:19 UTC, vainj commented on gnirps-origin/pom.xml
> +                    <version>${kotlin-maven-plugin.version}</version>
1/ Pourquoi faire la montée de version ici ? 
2/ Si cette dernière est nécessaire, pourquoi ne pas faire la modification ici `<kotlin.version>1.4.0</kotlin.version>` au lieu d'ajouter une nouvelle "properties" ?

2021-11-03 14:13 UTC, AdamJouenRL commented on gnirps-origin/pom.xml
> +                    <version>${kotlin-maven-plugin.version}</version>
1. J'ai eu des erreurs d'incompatibilité quand j'ai voulu faire le mvn install, j'ai corrigé les pom xml pour ne plus avoir les erreurs que j'ai eu. 
2. C'est kotlin maven plugin (https://search.maven.org/artifact/org.jetbrains.kotlin/kotlin-maven-plugin/1.6.0-RC2/maven-plugin) ici, non kotlin ici, c'est pour cela que les versions sont différentes.

2021-11-03 14:17 UTC, AdamJouenRL commented on gnirps-origin/pom.xml
> +        <maven-javadoc-plugin.version>3.3.1</maven-javadoc-plugin.version>
Je ne sais plus si c'était une nécessité absolue, mais j'ai eu des incompatibilités de versions entre les différents modules importés dans les différents modules de gnirps.

2021-11-03 14:19 UTC, AdamJouenRL commented on demos/cat-api-jwt/pom.xml
> +                <version>${kotlin-maven-plugin.version}</version>
Effectivement, peut être qu'il est possible de réutiliser les plugins utilisés dans gnirps origin, je sais pas comment faire si c'est le cas :/

2021-11-03 14:32 UTC, Pittinic commented on gnirps-origin/pom.xml
> +        <maven-javadoc-plugin.version>3.3.1</maven-javadoc-plugin.version>
La version 3.2.1 n'existe pas ; soit il y a eu dérapage du côté de celui qui l'a ajoutée sur Gnirps, soit elle a été supprimée (peu probable). La correction d'Adam est nécessaire !

2021-11-03 14:34 UTC, Pittinic commented on gnirps-origin/pom.xml
> +                    <version>${kotlin-maven-plugin.version}</version>
Une fois encore, il y avait un souci côté gnirps : la même propriété était effectivement utilisée pour gérer la version du langage et la version du plugin maven en question. C'a pu fonctionner par un heureux hasard tant que les deux versions existaient et étaient les mêmes ; ce n'est plus le cas aujourd'hui sur les versions les plus à jour.

Je ne suis pas sûr que la montée de version de kotlin soit nécessaire ; mais elle peut être intéressante tout de même, à déterminer !

2021-11-03 14:38 UTC, Pittinic requested changes
Avez-vous eu une vraie réflexion et discussion sur la façon de gérer les logs en JSON ? Si oui, je serais preneur d'un retour !

Je vois ici que dans le RestTemplateResponseErrorHandler, on part du postulat que le body d'une ClientHttpResponse est un json. Est-ce nécessairement le cas ? Ne serait-il pas judicieux de le vérifier d'abord, quitte à le JSONifier si ce n'est pas le cas ?

2021-11-03 16:15 UTC, vainj commented on gnirps-origin/pom.xml
> +                    <version>${kotlin-maven-plugin.version}</version>
Merci pour ces explications. 

En revanche, je ne suis pas certain de bien comprendre ta dernière phrase : 

> Je ne suis pas sûr que la montée de version de kotlin soit nécessaire ; mais elle peut être intéressante tout de même, à déterminer !

Sauf erreur de ma part, la version de Kotlin n'est pas modifiée dans cette PR (toujours en `<kotlin.version>1.4.0</kotlin.version>`) ?
Seule la version du plugin Maven de Kotlin va monter de version (1.4.0 --> 1.6.0-RC).

Du coup, ceci soulève d'autres questions : 

1. Est-ce que cette montée de version est vraiment nécessaire ? Pour rappel, le but premier de cette PR est un correctif mineur sur le format d'un log. Il ne faudrait pas que cette modification est un impact négatif sur la release/2.0.0 de Neuroo.
2. Si oui, n'est-ce pas plus sûr d'utiliser la dernière version stable "1.5.31" plutôt que la release candidate ?


**NB :** 

* https://kotlinlang.org/docs/releases.html#release-details : Pas de préconisation pour utiliser cette version du plugin Maven de Kotlin pour la version 1.4 du langage.
* https://kotlinlang.org/docs/maven.html#compile-kotlin-only-source-code : Dans les exemples de la doc Kotlin, il utilise la même "properties" pour la version du langage et le plugin Maven de Kotlin.

2021-11-03 16:31 UTC, vainj commented
> Avez-vous eu une vraie réflexion et discussion sur la façon de gérer les logs en JSON ? Si oui, je serais preneur d'un retour !

Non, pas dans les priorités du moment si je ne me trompe pas.

> Je vois ici que dans le RestTemplateResponseErrorHandler, on part du postulat que le body d'une ClientHttpResponse est un json. Est-ce nécessairement le cas ? Ne serait-il pas judicieux de le vérifier d'abord, quitte à le JSONifier si ce n'est pas le cas ?

En effet, si tu fait référence à la suppression des double-quotes, cela pourrait poser problème... J'essaie de regarder ça !

2021-11-03 17:21 UTC, Pittinic commented on gnirps-origin/pom.xml
> +                    <version>${kotlin-maven-plugin.version}</version>
Ah ! S'il y a une raison valable de conserver la même version du plugin que du langage, l'implémentation précédente était peut-être justifiée, après tout.

Je ne sais pas quoi penser du lien entre les deux versions pour l'instant. Je vous laisse juger pour l'instant si vous voulez avancer, et je me documenterai quand je pourrai !

Il y a quelques nouveautés sympas dans les dernières mises à jour du langage, mais je crois comprendre que ce n'est effectivement pas l'objet de la modification ici.

2021-11-04 13:36 UTC, Pittinic commented
PR abandonnée et remplacée par la 29 ?

2021-11-04 16:02 UTC, vainj commented
> PR abandonnée et remplacée par la 29 ?

Non, juste une PR créée beaucoup trop tôt entre les branches `dev` et `master` .

2021-11-04 16:02 UTC, vainj approved these changes

2021-11-08 13:27 UTC, Pittinic requested changes

2021-11-09 10:19 UTC, Pittinic approved these changes

2021-11-09 10:37 UTC, merged